### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by shahramlp** [0mWindyBug/FileHide#1]
Hi.
I did everything as you said
compiled the code without any changes and created ToHide folder and Hidden.sys and loaded the driver but it caused BSOD

**Comment by 0mWindyBug** [comment]
what was the bug check? what windows version are you using ? When did the BSOD occur ?

**Comment by 0mWindyBug** [comment]
> Hi.
> I did everything as you said
> compiled the code without any changes and created ToHide folder and Hidden.sys and loaded the driver but it caused BSOD

In addition , did you try using the compiled driver ? did it work?

**Comment by 0mWindyBug** [comment]
Closed due to no response
